"""empty message

Revision ID: 285bae154f90
Revises: 30f36fa03b17
Create Date: 2025-09-03 23:47:07.999802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '285bae154f90'
down_revision = '30f36fa03b17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resource_type', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.drop_column('resource_type')

    # ### end Alembic commands ###
