"""empty message

Revision ID: 342ada2d7fd5
Revises: 8be55fd70b78
Create Date: 2025-09-01 22:16:20.340504

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '342ada2d7fd5'
down_revision = '8be55fd70b78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('relief_requests', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('Pending', 'Approved', 'Fulfilled', name='request_status'),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_relief_requests_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('relief_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_relief_requests_status'))
        batch_op.alter_column('status',
               existing_type=sa.Enum('Pending', 'Approved', 'Fulfilled', name='request_status'),
               type_=mysql.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###
