"""empty message

Revision ID: 5318648344e1
Revises: e824b13806e7
Create Date: 2025-09-07 17:05:19.023458

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5318648344e1'
down_revision = 'e824b13806e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disasters', schema=None) as batch_op:
        batch_op.alter_column('severity',
               existing_type=mysql.ENUM('Low', 'Medium', 'High', 'Critical'),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disasters', schema=None) as batch_op:
        batch_op.alter_column('severity',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('Low', 'Medium', 'High', 'Critical'),
               existing_nullable=False)

    # ### end Alembic commands ###
