"""empty message

Revision ID: 98a1a3559b3e
Revises: 9fbb2440e68f
Create Date: 2025-09-07 15:54:38.486308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98a1a3559b3e'
down_revision = '9fbb2440e68f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disaster_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('severity', sa.Enum('Low', 'Medium', 'High', 'Critical', name='severity_levels'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reported_by', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['reported_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('disaster_reports')
    # ### end Alembic commands ###
