"""empty message

Revision ID: 9fd9981f7e8e
Revises: 6fb4bd467b30
Create Date: 2025-09-01 22:47:40.227603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fd9981f7e8e'
down_revision = '6fb4bd467b30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('donated_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['donated_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('donated_by')

    # ### end Alembic commands ###
