"""empty message

Revision ID: e824b13806e7
Revises: 98a1a3559b3e
Create Date: 2025-09-07 16:29:15.483393

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e824b13806e7'
down_revision = '98a1a3559b3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('disaster_reports')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disaster_reports',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('type', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('location', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('severity', mysql.ENUM('Low', 'Medium', 'High', 'Critical'), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('reported_by', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_on', mysql.DATETIME(), nullable=False),
    sa.Column('approved', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['reported_by'], ['users.id'], name=op.f('disaster_reports_ibfk_1'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
