"""empty message

Revision ID: faa9724494cd
Revises: 5318648344e1
Create Date: 2025-09-07 22:41:25.263953

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'faa9724494cd'
down_revision = '5318648344e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disasters', schema=None) as batch_op:
        batch_op.alter_column('updated_on',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_disasters_location'), ['location'], unique=False)
        batch_op.create_index(batch_op.f('ix_disasters_reported_by'), ['reported_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_disasters_severity'), ['severity'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disasters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_disasters_severity'))
        batch_op.drop_index(batch_op.f('ix_disasters_reported_by'))
        batch_op.drop_index(batch_op.f('ix_disasters_location'))
        batch_op.alter_column('updated_on',
               existing_type=mysql.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
